### ISSUE TITLE
Timeline divs are misaligned

### ISSUE THREAD

**Issue by offirgolan** [kockpit/ember-gantt#2]
From the demo page, the day, week, and year elements arent the expected size and therefore are misaligned.

<img width="1263" alt="screen shot 2018-10-17 at 3 45 37 pm" src="https://user-images.githubusercontent.com/575938/47120525-e146c500-d223-11e8-9a48-d5142660f957.png">

Adding a `min-width` that is the same as the set `width` seems to solve the misalignment.

**Comment by chvonrohr** [comment]
hi @offirgolan - thanks for the report.
I guess there's a date problem due to different timezones. It's all built using UTC timezone, but apparently there's still a miscalculation. 

![image](https://user-images.githubusercontent.com/1733057/47213343-8a3e0e80-d34f-11e8-9001-fe4c4c7fcb80.png)

**Comment by offirgolan** [comment]
No problem at all! The date miscalculation makes a lot more sense. I'm assuming if that gets resolved it should also fix #3 😄
