### ISSUE TITLE
can we display more than 1 data point per row?

### ISSUE THREAD

**Issue by PortNumber53** [kockpit/ember-gantt#6]
More of a question than an issue, per say, and hopefully it makes sense

say I want to use ember-gantt for scheduling and I need to display something like:

```
------------------------------------ usual calendar rows year/month/days--------------------------
johh doe               !------task 1-------!                               !------task 2-------- !
```

is this supported?

**Comment by chvonrohr** [comment]
Hi @PortNumber53 
Unfortunately, right now only one task per line is supported. What you can do is, have task 1 and two in separate lines, but have an aggregated line above (like in the demo here: https://kockpit.github.io/ember-gantt/).

Would this be sufficient for your case?

**Comment by PortNumber53** [comment]
Thanks for replying, it would for an MVP, but probably not in the long run.
