### ISSUE TITLE
Support for small time scales

### ISSUE THREAD

**Issue by ohhorob** [kockpit/ember-gantt#7]
Is there any current or planned way to use seconds/minutes/hours as the time scale, rather than days/weeks/months?

I'd like to use something like this to plan and visualise tasks that have short durations, down to tens of minutes.

**Comment by chvonrohr** [comment]
Unfortunately, the smallest unit so far is day and it's not planned to support smaller time scales.
Gantt is mostly used for longterm planning and therefore this was not part of the concept, sorry.
